### ISSUE TITLE
Could you release your training code?

### ISSUE THREAD

**Issue by dyxu-cuhkcse** [YzzLiu/FracSegNet#3]
Hi, thanks for you nice work.
I want to ask can you share your code for training?
Because now you only release the testing code and the pre-trained model.
I cannot re-implement the training process by myself.

Thanks!

**Comment by YzzLiu** [comment]
Sorry to have kept you waiting. We are conducting a comprehensive review of the training code to provide a more convenient version. We will release the training code as soon as possible.

If you are in a hurry, you can email me at yanzhenliu@buaa.edu.cn. I can give you a version for testing.

**Comment by WeiL233** [comment]
> Hi, thanks for you nice work. I want to ask can you share your code for training? Because now you only release the testing code and the pre-trained model. I cannot re-implement the training process by myself.
> 
> Thanks!

can you run the test code? i found some mistake reports in import part such as 'from fracSegNet.predict_single import predict_single_case'

**Comment by dyxu-cuhkcse** [comment]
> > Hi, thanks for you nice work. I want to ask can you share your code for training? Because now you only release the testing code and the pre-trained model. I cannot re-implement the training process by myself.
> > Thanks!
> 
> can you run the test code? i found some mistake reports in import part such as 'from fracSegNet.predict_single import predict_single_case'

I didn't run the test code yet. It's meaningless to inference without train code :)
