### ISSUE TITLE
nnuent是安装哪个版本的？

### ISSUE THREAD

**Issue by WeiL233** [YzzLiu/FracSegNet#4]
应该是v1的，但是model_restore.py对不上

**Comment by YzzLiu** [comment]
I apologize for the delay in addressing this issue. The nnunet version is 1.7.0 , and i have now uploaded the pickle file. You can find it [here](https://github.com/YzzLiu/FracSegNet/tree/main/code/inference).

**Comment by ark1234** [comment]
> 应该是v1的，但是model_restore.py对不上

兄弟，打扰您了，您能教教我这个怎么用么，有偿，我的扣扣是603315372， 微信是MianDianWang1953，非常感谢，祝研究顺利！
